[build]
  functions = "netlify/functions"
  publish = "dist"
  command = "npm run build"

[dev]
  functions = "netlify/functions"
  targetPort = 3000
  command = "npm run dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild" 