[build]
  functions = "netlify/functions"
  publish = "dist"

[dev]
  functions = "netlify/functions"
  command = "npm run dev"
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild" 